/**
 * AI Safety & Anti-Misuse
 * 
 * Safeguards:
 * - AI outputs are advisory only
 * - No AI-generated submissions allowed
 * - Flag suspicious patterns
 * - Cache AI outputs (no repeated calls)
 */

import { prisma } from '@/lib/prisma'

export interface SafetyCheckResult {
  allowed: boolean
  reason?: string
  flags?: string[]
}

/**
 * Check if user is attempting to submit AI-generated content
 */
export async function checkForAIGeneratedContent(
  userId: string,
  content: string
): Promise<SafetyCheckResult> {
  // Simple heuristics (can be enhanced)
  const suspiciousPatterns = [
    /generated by/i,
    /created by ai/i,
    /as an ai/i,
    /i am an ai/i,
    /i'm an ai/i,
  ]

  const flags: string[] = []

  for (const pattern of suspiciousPatterns) {
    if (pattern.test(content)) {
      flags.push('potential_ai_generated')
    }
  }

  // Check for unusually perfect formatting (heuristic)
  const lineBreaks = (content.match(/\n/g) || []).length
  const wordCount = content.split(/\s+/).length
  if (lineBreaks > wordCount / 10 && wordCount > 200) {
    // Very structured, might be AI-generated
    flags.push('suspicious_formatting')
  }

  if (flags.length > 0) {
    return {
      allowed: false,
      reason: 'Content may be AI-generated. Please submit your own original work.',
      flags,
    }
  }

  return {
    allowed: true,
  }
}

/**
 * Check rate limiting for AI calls
 */
export async function checkAIRateLimit(
  userId: string,
  maxCallsPerHour: number = 10
): Promise<SafetyCheckResult> {
  const oneHourAgo = new Date()
  oneHourAgo.setHours(oneHourAgo.getHours() - 1)

  const recentCalls = await prisma.activityLog.count({
    where: {
      userId,
      actionType: 'ai_insight_generated',
      createdAt: {
        gte: oneHourAgo,
      },
    },
  })

  if (recentCalls >= maxCallsPerHour) {
    return {
      allowed: false,
      reason: `Rate limit exceeded. Maximum ${maxCallsPerHour} AI calls per hour.`,
      flags: ['rate_limit_exceeded'],
    }
  }

  return {
    allowed: true,
  }
}

/**
 * Check for suspicious activity patterns
 */
export async function checkSuspiciousActivity(
  userId: string
): Promise<SafetyCheckResult> {
  const oneHourAgo = new Date()
  oneHourAgo.setHours(oneHourAgo.getHours() - 1)

  // Check for rapid-fire submissions
  const recentSubmissions = await prisma.idea.count({
    where: {
      userId,
      createdAt: {
        gte: oneHourAgo,
      },
    },
  })

  if (recentSubmissions > 10) {
    return {
      allowed: true, // Still allow, but flag
      flags: ['rapid_submissions'],
      reason: 'Unusually high submission rate detected',
    }
  }

  return {
    allowed: true,
  }
}

/**
 * Validate that AI output is advisory only
 */
export function validateAIOutputIsAdvisory(aiOutput: string): boolean {
  // Check for imperative language that suggests AI is doing work
  const forbiddenPatterns = [
    /here's the code/i,
    /here's your solution/i,
    /i've written/i,
    /i've created/i,
    /here's a complete/i,
  ]

  for (const pattern of forbiddenPatterns) {
    if (pattern.test(aiOutput)) {
      return false
    }
  }

  return true
}

/**
 * Sanitize AI output before storing
 */
export function sanitizeAIOutput(output: string): string {
  // Remove any potential code blocks that look like solutions
  let sanitized = output

  // Remove code blocks that are too long (might be solutions)
  sanitized = sanitized.replace(/```[\s\S]{200,}```/g, '[Code block removed - guidance only]')

  // Ensure output doesn't exceed reasonable length
  if (sanitized.length > 2000) {
    sanitized = sanitized.substring(0, 2000) + '...'
  }

  return sanitized.trim()
}

/**
 * Comprehensive safety check before AI call
 */
export async function performSafetyCheck(
  userId: string,
  content?: string
): Promise<SafetyCheckResult> {
  const checks = await Promise.all([
    checkAIRateLimit(userId),
    checkSuspiciousActivity(userId),
    ...(content ? [checkForAIGeneratedContent(userId, content)] : []),
  ])

  const failedCheck = checks.find(check => !check.allowed)
  if (failedCheck) {
    return failedCheck
  }

  const allFlags = checks.flatMap(check => check.flags || [])

  return {
    allowed: true,
    flags: allFlags.length > 0 ? allFlags : undefined,
  }
}
